import test from 'node:test';import assert from 'node:assert/strict';
import {validate,sheetValues,SHEET_HEADERS,syncLeads,allowedOrigin,authorizedWorker} from '../lib/campaign-leads.js';
const input=()=>({submission_id:'9ce3cbb2-aec2-4d25-a0d7-b4cd4cd5ac76',full_name:'QA Example',email:'QA@example.com',job_title:'Founder',company:'QA Company',business_description:'We sell software to companies.',industry:'technology',market:'global',revenue_band:'1m_5m',revenue_currency:'USD',solutions:['sales','operations'],consent:true,language:'en',attribution:{first:{utm_source:'newsletter',utm_campaign:'initial'},last:{utm_source:'openai',utm_medium:'paid',utm_campaign:'ai-growth',campaign_id:'campaign123',ad_group_id:'group123',ad_id:'ad123',click_id:'click123',page:'https://futureproofagents.com/ai-transformation/?email=private@example.com',referrer:'https://chatgpt.com/?private=1'}}});
test('inquiry keeps attribution while stripping unrelated query data',()=>{const p=validate(input());assert.equal(p.source,'openai');assert.equal(p.email,'qa@example.com');assert.equal(p.attribution.first.utm_source,'newsletter');assert.equal(p.attribution.last.referrer,'https://chatgpt.com/');assert.equal(p.attribution.last.ad_id,'ad123');assert.equal(p.attribution.last.page,'https://futureproofagents.com/ai-transformation/');assert.equal(p.consent_version,'inquiry-2026-10-06');});
test('both languages preserve currency and broad revenue ranges',()=>{const p=validate({...input(),language:'he',revenue_currency:'ILS',revenue_band:'undisclosed'});assert.equal(p.revenue_currency,'ILS');assert.equal(p.revenue_band,'undisclosed');assert.match(p.landing_page,/\/he\//);});
test('missing qualification, invalid LinkedIn, and missing consent fail validation',()=>{for(const patch of [{email:'invalid'},{job_title:''},{company:''},{business_description:'no'},{solutions:[]},{solutions:['made_up']},{revenue_band:'rich'},{consent:false},{linkedin_url:'https://linkedin.com.attacker.com/me'},{linkedin_url:'javascript:alert(1)'}])assert.throws(()=>validate({...input(),...patch}));assert.equal(validate({...input(),website_check:'bot'}).spam,true);});
test('origins and worker credential are scoped',()=>{assert.equal(allowedOrigin('https://attacker.vercel.app'),false);assert.equal(allowedOrigin('https://futureproofagents.com'),true);assert.equal(authorizedWorker('Bearer worker',{LEAD_SYNC_SECRET:'worker',LEAD_INGEST_SECRET:'ingest'}),true);assert.equal(authorizedWorker('Bearer ingest',{LEAD_SYNC_SECRET:'worker',LEAD_INGEST_SECRET:'ingest'}),false);});
const row=()=>({...validate(input()),id:'lead123',sheet_row:5,created_at:'2026-10-06T12:00:00Z',updated_at:'2026-10-06T12:00:00Z',status:'new',sync_status:'pending',version:1,notes:'',next_followup:null});
test('sheet row has exactly one column for each header and all required dimensions',()=>{const values=sheetValues(row());assert.equal(values.length,SHEET_HEADERS.length);assert.equal(values[20],'group123');assert.equal(values[27],'click123');assert.equal(values[23],'newsletter');});
const fixture=({fail=false,moved=false,headerChanged=false}={})=>{const calls=[],lead=row();return {calls,env:{CAMPAIGN_SHEET_ID:'sheet'},rpc:async(name,args)=>{calls.push([name,args]);return name==='fp_campaign_claim'?[lead]:null;},sheetTool:async(name,args)=>{calls.push([name,args]);if(name==='GOOGLESHEETS_GET_SPREADSHEET_INFO')return {sheets:[{properties:{title:'Leads',gridProperties:{rowCount:1000}}}]};if(name==='GOOGLESHEETS_VALUES_GET')return {values:[args.range.endsWith('A1:AF1')?(headerChanged?['Changed']:SHEET_HEADERS):moved?['someone_else']:['lead123']]};if(fail)throw Error('timeout');return {updatedRows:1};}};};
test('sheet sync uses fixed rows and RAW input',async()=>{const d=fixture();assert.equal((await syncLeads(null,d)).synced,1);const write=d.calls.find(x=>x[0]==='GOOGLESHEETS_VALUES_UPDATE')[1];assert.equal(write.value_input_option,'RAW');assert.equal(write.range,"'Leads'!A5:AF5");});
test('uncertain sheet failure remains queued for idempotent retry',async()=>{const d=fixture({fail:true});assert.equal((await syncLeads(null,d)).synced,0);assert.equal(d.calls.at(-1)[1].succeeded,false);assert.equal(d.calls.at(-1)[1].error_code,'sheets_unavailable');});
test('moved rows and changed headers cannot overwrite other records',async()=>{for(const patch of [{moved:true},{headerChanged:true}]){const d=fixture(patch);await syncLeads(null,d);assert.equal(d.calls.some(c=>c[0]==='GOOGLESHEETS_VALUES_UPDATE'),false);}});

test('form API allows the Render domain preflight and blocks unrelated origins',async()=>{const {default:handler}=await import('../api/lead.js');const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.code=v;return this;},end(){},json(v){this.body=v;}});for(const [origin,code] of [['https://futureproofagents.com',204],['https://evil.example',403]]){const res=response();await handler({method:'OPTIONS',headers:{origin}},res);assert.equal(res.code,code);assert.equal(res.headers['Access-Control-Allow-Origin'],code===204?origin:undefined);}});

test('internal navigation is not misreported as a referral',()=>{for(const referrer of ['https://futureproofagents.com/blog/','https://www.futureproofagents.com/']){const p=validate({...input(),attribution:{first:{referrer},last:{referrer}}});assert.equal(p.source,'direct');assert.equal(p.medium,'none');assert.equal(sheetValues({...row(),...p})[23],'direct');}assert.equal(validate({...input(),attribution:{last:{referrer:'https://chatgpt.com/'}}}).source,'chatgpt.com');});

test('shorter form accepts omitted market, industry and challenge without inventing answers',()=>{const body=input();delete body.market;delete body.industry;delete body.challenge;const p=validate(body);assert.equal(p.market,'');assert.equal(p.industry,'');assert.equal(p.challenge,'');assert.equal(sheetValues({...row(),...p})[9],'');assert.equal(validate(input()).market,'global');});

const accounting=()=>({...input(),form_type:'accounting_us',team_size:'5_10',project_budget:'10k_25k',current_software:'TaxDome and Microsoft 365',firm_website:'https://example.com/?private=value',challenge:'Connect incoming client documents to our workflow.',attribution:{first:{utm_source:'google',gclid:'test-click'},last:{utm_source:'google',utm_medium:'cpc',utm_campaign:'us-accounting',gclid:'test-click',gbraid:'test-braid'}}});
test('accounting qualification survives existing database and sheet fields with Google attribution',()=>{const p=validate(accounting());assert.equal(p.landing_page,'https://futureproofagents.com/ai-for-accounting-firms/');assert.equal(p.source,'google');assert.equal(p.attribution.last.gclid,'test-click');assert.equal(p.attribution.last.gbraid,'test-braid');assert.equal(p.market,'north_america');assert.match(p.challenge,/\$10,000–\$25,000/);assert.match(p.challenge,/TaxDome and Microsoft 365/);assert.ok(!p.challenge.includes('private=value'));assert.equal(sheetValues({...row(),...p})[13],p.challenge);assert.equal(sheetValues({...row(),...p})[25],p.landing_page);});
test('accounting cannot submit incomplete budget or software details, unsafe URLs or oversized text',()=>{for(const patch of [{team_size:''},{project_budget:'free'},{current_software:''},{challenge:'short'},{firm_website:'javascript:alert(1)'},{language:'he'},{current_software:'x'.repeat(201)},{challenge:'x'.repeat(1001)}])assert.throws(()=>validate({...accounting(),...patch}));});
